### PR TITLE
Ability to stop DS4Windows for certain programs

### PR DESCRIPTION
**Pull request by dedChar**
Some games come with their own detection of the ds4 controller now so I added a way of disabling DS4Windows for selected games using the Auto Profiles tab.

### CODE REVIEW

**Comment by emzero** [comment]
It seems the developer is no longer working on this program. 
Too bad, it's a great program.

**Comment by Jays2Kings** [comment]
This seems like a good feature to add, however the way this is done isn't optimal.

Having DS4Windows stop itself in a loop means it starts and stops all the controllers 1-4 times. The method to do this is also unclear to users.

I will attempt to add this feature in a more clear way in the future.

**Comment by dedChar** [comment]
Yeah, I totally agree that my implementation isn't really good. I just thought this was a missing feature and since there was already an issue made on that matter (#97), I decided to share it until you (or someone else) does it better. :)

**Comment by Jays2Kings** [comment]
As of 1.4.5 I've added a cleaner option for this into the auto profiles tab.

**Pull request closed without merging**
